### ISSUE TITLE
State of this library

### ISSUE THREAD

**Issue by venkatd** [mariposa-dart/mariposa#16]
Hi @thosakwe we've got a Flutter web app which works well for most of our use cases. However, there are a few situations where a lightweight web app would load faster and make more sense for us. 

We could React, but then we wouldn't be able to take advantage of our business logic. What's your opinion on how this library turned out? It's feasible to have a react substitute but with with an API similar to Flutter?

What's the state of this library? Are there any gotchas to be aware of?

**Comment by thosakwe** [comment]
Hi Venkat, this library is no longer maintained. I would say it's feasible to have a Flutter-like React substitute, yes. I would recommend just going with AngularDart, though, since it already has routing, forms, and other features.

Anyways, I should probably archive this repository, since it's no longer being used. Send me an email if you have any more questions.
